## List Comprehension

In [6]:
nm = [1,2,3,4]
newnm = list();
#print the squares of the number

In [7]:
for i in nm:
    print(i*i)

1
4
9
16


In [10]:
nm = [1,2,3,4]
newnm = list();
#print a list to hold the squares of the number

In [11]:
for i in nm:
    newnm.append(i*i)
    
newnm

[1, 4, 9, 16]

In [12]:
#new = [output iterable]
new = [i**2 for i in nm]
print(new)

[1, 4, 9, 16]


In [14]:
num = [1,2,3,4,5,6,7,8,9]
nk1 = list()
#generate a list with square of the numbers
#but consider only even numbers

In [15]:
for i in num:
    if(i % 2 == 0):
        nk1.append(i**2)
print(nk1)
        

[4, 16, 36, 64]


In [18]:
#list comprehension
#new = [output iterable condition]

In [17]:
new =[i**2 for i in num if(i%2==0)]
new

[4, 16, 36, 64]

### Q3

In [19]:
prices = [100,200,250,300,450]
#Add 7% GST to each value and generate new list

In [20]:
taxpr = [i*0.07+i for i in prices]

In [21]:
taxpr

[107.0, 214.0, 267.5, 321.0, 481.5]

### Q4

In [30]:
text = "Assets is worth 24000000 and liability is 120000"

#using list comprehension extract allnumberfrom the string

In [33]:
opnum = [int(i) for i in text.split() if(i.isdigit())]

In [34]:
opnum

[24000000, 120000]

In [35]:
#Generate a list of ROI:10% for term deposits
#15% for Gov Bonds,20% for Tbills
investments = ["GBonds","Tbills","Term","Term","TBills"]

In [36]:
roi = [0.15 if i=="GBonds" else 0.2 if i=="TBills"\
      else 0.10 for i in investments]
roi

[0.15, 0.1, 0.1, 0.1, 0.2]

### User Defined Function

In [47]:
def srm_add():
    price =100;
    tax=7;
    total = price+tax;
    print(total)

In [43]:
srm_add() # call by reference 

107


In [51]:
def srm_add(price,tax):
    total = price+tax;
    print(total)

In [52]:
srm_add(100,7) #call by value using the values and calling the srm_add method

107


In [53]:
def srm_add1(price,tax):
    total = price+tax;
    return(total)

In [54]:
result = srm_add1(100,30)

In [55]:
result

130

In [56]:
#can you write a function
#that can store a string 
#and return the list of digits if digits are present in string

In [59]:
def srm_DigitExtractor(inputstr):
    opnum = [int(i) for i in inputstr if(i.isdigit())]
    return(opnum)
    

In [61]:
srm_DigitExtractor("Hello this is 12345 say hi to my friends 34567 and 89012")

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]

## Keyworded Arguement

In [5]:
def srm1_add(total,qty):
    unit=total/qty;
    return(unit)

In [7]:
z=srm1_add(300,10)
z

30.0

In [8]:
z=srm1_add(total=3000,qty=12)//Keyworded arguements

In [9]:
z

250.0

## Default Arguement

In [15]:
def srm_rate(total,qty=10):
    #default values for qty in case value not passed
    unit = total/qty
    return(unit)

In [18]:
z=srm_rate(300)#default in case value for qty is not passed
z

30.0

In [19]:
z=srm_rate(300,30)#default in case value for qty is not passed
z

10.0

## Variable length Arguement

In [20]:
def srm_add_all(*num):
    print(num)

In [21]:
srm_add_all(5,6,7)

(5, 6, 7)


Write a program to add all input and return the value

In [25]:
def srm_add_all(*num):
    count = 0
    for i in num:
        count += i;#count=count+i
    return count;

In [26]:
z=srm_add_all(3,4,5,6,7,8,9)

In [27]:
z

42

### Variable length Keyworded Arguement

In [28]:
def srm_data(**info):
    print(info)

In [29]:
srm_data(name="John",age=20,qlf="Masters")

{'name': 'John', 'age': 20, 'qlf': 'Masters'}


### Returning multiple values

In [30]:
def srm_values(rate,tax,qty):
    cost_bef_tax = rate*qty;
    cost_aft_tax = cost_bef_tax+tax;
    return(cost_bef_tax,cost_aft_tax)

In [31]:
cbt,cat=srm_values(10,500,1000)

In [32]:
print(cbt)
print(cat)

10000
10500


### Lambda Functions

In [33]:
lambda x:x+1

<function __main__.<lambda>(x)>

In [34]:
result = lambda x:x+1
result(8)

9

In [35]:
result =lambda x:x**2+1+x**3+5
result(10)

1106

In [38]:
fn = "mark"
ln = "jeffrey"
fullname = lambda fn,ln: fn.title()+" "+ln.title()
fullname(fn,ln)

'Mark Jeffrey'

In [39]:
names = ["Ramesh Nair","John Taylor","Swathi Reddy","Manash Kumar"]
names.sort()

In [45]:
names

['John Taylor', 'Manash Kumar', 'Ramesh Nair', 'Swathi Reddy']

In [48]:
lname=list()
for i in names:
    temp=i.split(" ")
    lname.append(temp[1])
lname.sort()
lname

['Kumar', 'Nair', 'Reddy', 'Taylor']

In [49]:
names.sort(key=lambda x:x.split(" ")[1])

In [50]:
names

['Manash Kumar', 'Ramesh Nair', 'Swathi Reddy', 'John Taylor']

In [51]:
names1 = ['John Kennedy Taylor', 'Manash Kumar', 'Ramesh Nair', 'Swathi Reddy']
names1.sort(key=lambda x:x.split(" ")[-1])
names1

['Manash Kumar', 'Ramesh Nair', 'Swathi Reddy', 'John Kennedy Taylor']

#### Q7

In [55]:
items=[("apples",87),("oranges",54),("grapes",59),("Kiwi",117)]

#sort list by using amount

In [57]:
items.sort(key=lambda x:x[-1])

In [58]:
items

[('oranges', 54), ('grapes', 59), ('apples', 87), ('Kiwi', 117)]

### Q8

In [69]:
emp=[{'name':'John','age':23,'YOJ':2016},\
   {'name':'mary','age':32,'YOJ':2019},\
   {'name':'Tommy','age':19,'YOJ':2017},\
   {'name':'Henry','age':40,'YOJ':2020}]
# sort by Yoj

In [70]:
emp.sort(key=lambda x:x['YOJ'], reverse=True)
emp

[{'name': 'Henry', 'age': 40, 'YOJ': 2020},
 {'name': 'mary', 'age': 32, 'YOJ': 2019},
 {'name': 'Tommy', 'age': 19, 'YOJ': 2017},
 {'name': 'John', 'age': 23, 'YOJ': 2016}]

## Numpy python

In [1]:
import numpy as np
weight = [57,62,73,64]
print('Type of Weight:',type(weight))

weight_array = np.array(weight)
print('weight_array:',weight_array)
print('Type of weighht array',type(weight_array))

Type of Weight: <class 'list'>
weight_array: [57 62 73 64]
Type of weighht array <class 'numpy.ndarray'>


In [2]:
print(weight)
print(weight_array)

[57, 62, 73, 64]
[57 62 73 64]


In [13]:
np.random.random(size = 10)

array([0.91670284, 0.73846841, 0.15176502, 0.60377569, 0.86700957,
       0.72545739, 0.44969432, 0.06310821, 0.92639733, 0.43282245])

In [11]:
np.random.rand(5)

array([0.23948956, 0.17602131, 0.3183151 , 0.83915316, 0.48648986])

In [15]:
a=np.random.randn(5)

In [16]:
a.mean()

-0.003690545011925095

In [17]:
np.random.randint(5,20)

10

In [2]:
np.random.randint(20,50,5)

array([25, 25, 34, 40, 42])

In [2]:

even_num = np.arange(start = 10,stop = 20,step = 2)
even_num

array([10, 12, 14, 16, 18])

In [5]:
np.linspace(start = 0,stop = 50,num = 20)

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [10]:
q=np.zeros(6)

In [11]:
q.shape

(6,)

In [26]:
matrix_empty = np.empty((2,3),dtype= int)
matrix_empty

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
matrix_empty.ndim

2

In [30]:
original_shape =np.array([(4,9),(7,2),(5,6)])
print("original array:",original_shape)

reshaped_array =original_shape.reshape(2,3)
print("reshaped_array:",reshaped_array)

original array: [[4 9]
 [7 2]
 [5 6]]
reshaped_array: [[4 9 7]
 [2 5 6]]


In [32]:
#consider a 1D array
age = np.array([23,45,18,26,34,65])

#retrive the 1 st element
print('First Element:',age[0])

First Element: 23


In [34]:
# CONSIDER a 2D array
weight = np.array([(51,45,68),(62,74,55)])

a12 = weight[0][1]
print('a12 :',a12)

print('second row:', weight[1,:])

a12 : 45
second row: [62 74 55]


In [35]:
a1 = np.array([(10,20,30),(40,50,60),(70,80,90)])

In [36]:
a1[1:,:2]

array([[40, 50],
       [70, 80]])

In [37]:
#array filtering
#array_name[array_name(>/</==)number]<---- filteration bracket
#               |----> condition

In [38]:
age = np.array([13,45,22,6,14,25])

print('Boolean output:',age>18)

Boolean output: [False  True  True False False  True]


In [39]:
print('age greater than 18:',age[age>18])

age greater than 18: [45 22 25]


### arithmatic operations on array

In [42]:
odd_num = np.array([3,7,5,9])
even_num = np.array([8,10,4,2])

In [43]:
sum = odd_num +even_num
print('Addition:',sum)

Addition: [11 17  9 11]


In [44]:
sub = odd_num -even_num
print('Subraction:',sub)

Subraction: [-5 -3  1  7]


In [45]:
num_array = np.array([1,2,3,4,5])
print('updated_array:',num_array*2)

updated_array: [ 2  4  6  8 10]


In [47]:
num_matrix_1 = np.array([[1,0,2],[4,-2,3]])
num_matrix_2 = np.array([[4,0,1],[2,3,0]])

prod=num_matrix_1*num_matrix_2

In [48]:
print('element wise multiplication:\n',prod)

element wise multiplication:
 [[ 4  0  2]
 [ 8 -6  0]]


### airthmatic functions

In [49]:
age = np.array([14,74,84,26,56])
print("Minimum:",age.min())

Minimum: 14


In [50]:
age = np.array([14,74,84,26,56])
print("Maximum:",age.max())

Maximum: 84


In [51]:
age = np.array([14,74,84,26,56])
print("sum of all elements:",age.sum())

sum of all elements 254


In [53]:
print("mean:",age.mean())

mean: 50.8


In [55]:
print("Variance:",age.var())

Variance: 727.36


In [56]:
print("Standard deviation",age.std())

Standard deviation 26.969612529660118


In [57]:
print("Square",np.square(age))---Squre matrix of age

Square [ 196 5476 7056  676 3136]


In [58]:
print("cube",np.power(age,3))

cube [  2744 405224 592704  17576 175616]


In [59]:
print("4thPow:",np.power(age,4))

4thPow: [   38416 29986576 49787136   456976  9834496]


In [60]:
num_matrix

NameError: name 'num_matrix' is not defined

In [61]:
who

a1	 a12	 age	 even_num	 matrix_empty	 np	 num_array	 num_matrix_1	 num_matrix_2	 
odd_num	 original_shape	 prod	 q	 reshaped_array	 sub	 sum	 weight	 weight_array	 



In [63]:
import pandas as py
num_matrix_1.transpose()


array([[ 1,  4],
       [ 0, -2],
       [ 2,  3]])

In [67]:
num_matrix_1.T

array([[ 1,  4],
       [ 0, -2],
       [ 2,  3]])

### Concatinate a 1D array

In [68]:
order_1 = np.array([1,4,5,7])
order_2 = np.array([6,9,3])
order_3 = np.array([2,7,5,9])

np.concatenate((order_1,order_2,order_3))

array([1, 4, 5, 7, 6, 9, 3, 2, 7, 5, 9])

In [69]:
odd_array= np.array([[1,3],
                     [5,7]])

In [70]:
even_array = np.array([[2,4],
                       [6,8]])

In [75]:
#concatinate along row wise
print('concatinate row wise:',np.concatenate([odd_array,even_array]))

concatinate row wise: [[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [76]:
#concatinate column wise
print('concatinate column wise:',np.concatenate([odd_array,even_array],axis=1))

concatinate column wise: [[1 3 2 4]
 [5 7 6 8]]


In [4]:
def sam(n):
    return ((abs(100 - n) <= 10) or (abs(200 - n) <= 10))

In [5]:
sam(90)

True

In [6]:
sam(150)

False

In [7]:
sam(200)

True

In [8]:
sam(100)

True

In [9]:
def func():

     print("You are welcome to func")

     print(var)

func()

You are welcome to func


NameError: name 'var' is not defined

In [11]:
min = (lambda x, y: x if x < y else y)

min(101*99, 102*98)

9996

In [12]:
def random(text):

      sample = text.split()

      return sample[0][0] == sample[1][0]

In [13]:
random('false false')

True

In [14]:
random('hi ih')

False

In [15]:
random('true true')

True

In [22]:
def random(f):
    print(type(f))
    print('This is wrong')
        

def sample():

      print('This is correct')


In [23]:
ans = random(sample)

ans

<class 'function'>
This is wrong


In [24]:
numbers = [1, 2, 3]

In [25]:
list(filter(lambda x: x % 2 == 0, numbers))

[2]

In [26]:
list(filter(lambda x: 2, numbers))

[1, 2, 3]

In [27]:
list(filter(lambda x: x > 1, numbers))

[2, 3]

In [28]:
my_string = "hello world"

k = [(i.upper(), len(i)) for i in my_string]

print(k)

[('H', 1), ('E', 1), ('L', 1), ('L', 1), ('O', 1), (' ', 1), ('W', 1), ('O', 1), ('R', 1), ('L', 1), ('D', 1)]


In [1]:
19-15

4

In [2]:
19+(1.5*4)

25.0